Lab1
annikura/java pull request #1
Opened 2017-09-18 22:54 UTC by annikura

2017-09-25 05:07 UTC, jzuken requested changes

2017-09-25 05:07 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/hashtable/HashTable.java
> +import java.beans.VetoableChangeListener;
а это тут зачем?

2017-09-25 05:07 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/hashtable/HashTable.java
> +  private Vector<KeyValueList<String, String>> tableContent = new Vector<>();
а зачем тут вектор? массива бы вполне хватило, как по мне

2017-09-25 05:07 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/list/Entry.java
> +public class Entry<KeyType, ValueType> {
я бы назвал этот класс Pair и сделал бы его нормальным классом, ну то есть без этого мрака с публичными полями. а то имя Entry наталкивает на мысли, что это что-то связанное с реализацией списка

2017-09-25 05:07 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/list/ListNode.java
> +public class ListNode<ValueType> {
а вот этот класс как раз и есть детали реализации списка, его бы очень не хотелось светить кому-то за него пределами. давайте уберём его из интерфейса списка так, чтобы методы только Entry возвращали? то есть работали только с данными про которые хорошо знают их клиенты

2017-09-25 05:07 UTC, jzuken commented on HashTable/src/tests/ru/spbau/annikura/hashtable/HashTableTest.java
> +public class HashTableTest {
ещё хочется тест на коллизии и на перестраивание таблицы

2017-09-30 19:13 UTC, annikura commented on HashTable/src/ru/spbau/annikura/hashtable/HashTable.java
> +import java.beans.VetoableChangeListener;
Fixed.

2017-09-30 19:13 UTC, annikura commented on HashTable/src/ru/spbau/annikura/hashtable/HashTable.java
> +  private Vector<KeyValueList<String, String>> tableContent = new Vector<>();
Мне в какой-то момент времени IDE кидало ошибки по поводу создания массива от generic'a. Теперь поменяла на массив. Fixed.

2017-09-30 19:13 UTC, annikura commented on HashTable/src/ru/spbau/annikura/list/ListNode.java
> +public class ListNode<ValueType> {
Done. Добавила в лист итератор.

2017-09-30 19:13 UTC, annikura commented on HashTable/src/tests/ru/spbau/annikura/hashtable/HashTableTest.java
> +public class HashTableTest {
Done.

2017-09-30 19:14 UTC, annikura commented on HashTable/src/ru/spbau/annikura/list/Entry.java
> +public class Entry<KeyType, ValueType> {
Поменяла название на Pair. Правда, если честно, мне кажество, что делать Pair с полями key и  value -- это немного странно. Fixed?

2017-10-07 15:57 UTC, jzuken requested changes

2017-10-07 15:57 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/list/ListIterator.java
> +    public ListIterator(ListNode<T> node) {
класс итератора обычно делают внутренним классом того, что он итерирует. тогда не придётся раскрывать детали реализации и показывать всем остальным ноды

2017-10-07 15:57 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/list/ListNode.java
> +public class ListNode<ValueType> {
эм. мы говорили о том, чтобы спрятать этот класс как деталь реализации, а он внезапно public в пакете, да и итератор его явно принимает

2017-10-07 15:57 UTC, jzuken commented on HashTable/src/tests/ru/spbau/annikura/hashtable/HashTableTest.java
> +public class HashTableTest {
вообще тесты -- это отдельная задача, и под неё нужно сделать отдельный бранч и пуллреквест. это специально было сделано так, чтобы вы с гитом поработали дополнительно

2017-10-14 11:52 UTC, annikura commented on HashTable/src/ru/spbau/annikura/list/ListIterator.java
> +    public ListIterator(ListNode<T> node) {
И ноды, и итератор сделала package-private. Я не хочу делать их внутренними т.к. они универсальны для любого листа и если я его туда захочу дописать, мне не придётся превращать эти классы обратно в самостоятельные. Есть какая-то принципиальная разница и обязательно нужно написать абстрактный лист, туда положить итератор и от него уже наследовать мой key-value-list или так тоже нормально?

Тесты перенесла в тот же package, ибо node я всё-таки хочу тестировать.
Не очень поняла, в чём проблема того, что итератор принимает ноду, при условии, что они спокойно живут в одном пакете и оба не светятся.

2017-10-14 11:52 UTC, annikura commented on HashTable/src/tests/ru/spbau/annikura/hashtable/HashTableTest.java
> +public class HashTableTest {
И предлагается потом между двумя этими ветками каждый раз rebas'иться? Я тесты сюда написала изначально (потому что не очень понятно, как понимать хоть что-то о работоспособности программы без тестов), и только потом увидела, что это дз. Окей, вынесу в отдельную ветку.

2017-10-16 14:48 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/list/ListIterator.java
> +    public ListIterator(ListNode<T> node) {
"они универсальны для любого листа" -- а вот неправда. они универсальны для любого списка, который реализуется ровно так же, как этот. а если это станет не двусвязный список, а какой-нибудь другой, то вы же всё равно захотите новую ноду сделать, нет?

2017-10-22 12:52 UTC, jzuken requested changes

2017-10-22 12:52 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/hashtable/HashTable.java
> +   * @param key
для параметров вроде как тоже нужны доки

2017-10-22 12:52 UTC, jzuken commented on HashTable/src/tests/ru/spbau/annikura/TestRunner.java
> +    ListNodeTest.createNode();
а этот зачем?

2017-10-22 12:52 UTC, jzuken commented on HashTable/src/ru/spbau/annikura/list/ListNodeTest.java
> +public class ListNodeTest {
мы вроде бы договорились, что вы вынесете тесты из этой ветки в другую?

2017-10-27 07:54 UTC, annikura commented on HashTable/src/ru/spbau/annikura/hashtable/HashTable.java
> +   * @param key
Done

2017-10-27 07:56 UTC, annikura commented on HashTable/src/tests/ru/spbau/annikura/TestRunner.java
> +    ListNodeTest.createNode();
Нам тогда ещё системы сборки не подвезли. А хотелось как-то запускать все тесты сразу. Удалила.

2017-10-27 09:38 UTC, jzuken commented on HashTable/src/tests/ru/spbau/annikura/TestRunner.java
> +    ListNodeTest.createNode();
система сборки тут не при чём. тесты вполне можно запустить из IDE, командной строки или другого класса: 
https://stackoverflow.com/questions/2235276/how-to-run-junit-test-cases-from-the-command-line. 
https://stackoverflow.com/questions/2543912/how-do-i-run-junit-tests-from-inside-my-java-application

2017-11-06 10:28 UTC, merged