Lab7
annikura/java pull request #10
Opened 2017-11-07 21:57 UTC by annikura

2017-11-18 13:33 UTC, jzuken requested changes

2017-11-18 13:33 UTC, jzuken commented on FP/src/main/java/ru/spbau/annikura/function/Function1.java
> +    public R apply(/*Nullability is not known, function-defined*/ T arg);
ну если is not known, то ничего и не пишем тут :)
вкопипащивать комментарий везде как-то странно выглядит

2017-11-18 13:33 UTC, jzuken commented on FP/src/main/java/ru/spbau/annikura/function/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = arg -> true;
а тут у генерика параметр-тип не потерялся?

2017-11-27 05:19 UTC, annikura commented on FP/src/main/java/ru/spbau/annikura/function/Function1.java
> +    public R apply(/*Nullability is not known, function-defined*/ T arg);
Ну как вам сказать. Система оценки, основанная всё-таки по большей части на кнуте (Дональд тут ни при чём), а не на равноправном обсуждаении существующих проблем, порождает свои эксцессы.

Если бы без этих комментариев моё намерение не определять там Nullability вы восприняли бы как мою забывчивость, баллы автоматически потеряла бы я (чего мне не очень хочется) и чёрта с два там докажешь. А сделать один поиск по проекту и удалить все одинаковые накопипасченные строчки нетрудно, зато гарантирует результат.

2017-11-27 05:25 UTC, annikura commented on FP/src/main/java/ru/spbau/annikura/function/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = arg -> true;
Вы меня заставили задуматься. В задании написано, что можно методом, а не полем. Что, наверное, подразумевает, что можно добиться нужного результата (избежать unchecked warnings при каждом использовании таких полей), правильно их определив. Я так не умею, а это вообще возможно?

2017-11-27 11:22 UTC, jzuken commented on FP/src/main/java/ru/spbau/annikura/function/Function1.java
> +    public R apply(/*Nullability is not known, function-defined*/ T arg);
а вы их когда убирать собирались?
ну и во-вторых, если неизвестно ничего про значения, так мы и предполагаем, что может быть всё, что угодно. :) то есть Nullable или ничего, если им не пользуемся
да ладно, это не критичное замечание, просто глаз резануло

2017-11-27 11:27 UTC, jzuken commented on FP/src/main/java/ru/spbau/annikura/function/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = arg -> true;
давайте я немного подскажу: https://docs.oracle.com/javase/tutorial/java/generics/wildcards.html

2017-11-27 16:54 UTC, annikura commented on FP/src/main/java/ru/spbau/annikura/function/Function1.java
> +    public R apply(/*Nullability is not known, function-defined*/ T arg);
Так их там нет. Вы смотрите на свежую версию pr или старую?

2017-11-27 16:57 UTC, annikura commented on FP/src/main/java/ru/spbau/annikura/function/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = arg -> true;
Статические методы, обобщенные по параметру, возвращающие эти поля, есть в свежей версии. Статические параметризованные поля невозможны. Так что либо у вас старая версия, либо я не поняла намёка.

2017-11-27 16:59 UTC, annikura commented on FP/src/main/java/ru/spbau/annikura/function/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = arg -> true;
Собственно, FP/src/main/java/ru/spbau/annikura/function/Predicate.java:20 и FP/src/main/java/ru/spbau/annikura/function/Predicate.java:36

2017-11-29 11:34 UTC, jzuken commented on FP/src/main/java/ru/spbau/annikura/function/Function1.java
> +    public R apply(/*Nullability is not known, function-defined*/ T arg);
да не, я про первую говорил изначально

2017-11-29 11:39 UTC, jzuken commented on FP/src/main/java/ru/spbau/annikura/function/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = arg -> true;
всё нормально, да. я ещё проглядел, что это интерфейс

2017-11-29 11:52 UTC, annikura commented on FP/src/main/java/ru/spbau/annikura/function/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = arg -> true;
А что исправлять-то? Замечаний ведь больше нет, я правильно понимаю?

2017-11-29 12:57 UTC, merged