Pool request
annikura/java pull request #17
Opened 2018-03-08 22:22 UTC by annikura

2018-03-17 08:01 UTC, jzuken requested changes

2018-03-17 08:01 UTC, jzuken commented on lazy/src/main/java/ru/spbau/annikura/utils/RuntimeExceptionOr.java
> +public class RuntimeExceptionOr<T> {
смысл этого класса понятен, но имя как-то обрывается на самом интересном :)

2018-03-17 08:01 UTC, jzuken commented on lazy/src/main/java/ru/spbau/annikura/threadpool/Pool.java
> +    private final ArrayList<LightFutureImpl> tasks = new ArrayList<>();
а эти константы не заслужили именоваться капсом?

2018-03-17 08:01 UTC, jzuken commented on lazy/src/main/java/ru/spbau/annikura/threadpool/Pool.java
> +        private final Lazy<RuntimeExceptionOr<T>> lazy;
о, ну хоть кто-то догадался, что тут Lazy можно использовать :)

2018-03-17 08:01 UTC, jzuken commented on lazy/src/main/java/ru/spbau/annikura/lazy/ThreadSafeLazy.java
> +        if (!object.isEmpty()) {
ему volatile бы не помешало добавить

2018-03-24 21:37 UTC, annikura commented on lazy/src/main/java/ru/spbau/annikura/utils/RuntimeExceptionOr.java
> +public class RuntimeExceptionOr<T> {
Кажется, это первый раз на моей практике, когда идеальное для плюсов название (в них же никак иначе кроме ExceptionOr<Type> не напишешь, что прекрасно читалось) не подходит для джавы. Переименовала.

2018-03-24 21:39 UTC, annikura commented on lazy/src/main/java/ru/spbau/annikura/threadpool/Pool.java
> +    private final ArrayList<LightFutureImpl> tasks = new ArrayList<>();
Я думаю, что не заслужили. Они действительно final, но не static. Да и по коду используются совсем не как константы. Вы хотите, чтобы я это сделала или это был абстрактный вопрос?

2018-03-24 21:39 UTC, annikura commented on lazy/src/main/java/ru/spbau/annikura/lazy/ThreadSafeLazy.java
> +        if (!object.isEmpty()) {
Добавила в другой ветке, вмержила сюда.

2018-03-25 06:36 UTC, jzuken commented on lazy/src/main/java/ru/spbau/annikura/threadpool/Pool.java
> +    private final ArrayList<LightFutureImpl> tasks = new ArrayList<>();
да не, мне просто интересно было, можно не менять

2018-04-04 09:33 UTC, jzuken commented
а теперь тут конфликты после мерджа lazy в мастер :)

2018-04-15 13:35 UTC, merged