Lab2
annikura/java pull request #2
Opened 2017-09-27 20:39 UTC by annikura

2017-10-07 15:25 UTC, jzuken requested changes

2017-10-07 15:25 UTC, jzuken commented on Spiral/src/test/java/ru/spbau/annikura/spiral/CoordinateTest.java
> +package test.java.ru.spbau.annikura.spiral;
эээ, нет, test.java тут лишнее. эти каталоги не входят в название пакета, и поэтому, кстати, мавен не видит ваши тесты (попробуйте выполнить mvn install и увидите Tests run: 0, Failures: 0, Errors: 0, Skipped: 0)

сама идея, кстати, подчёркивает эту строчку

2017-10-07 15:25 UTC, jzuken commented on Spiral/src/main/java/ru/spbau/annikura/spiral/Spiral.java
> +    public static void PrintUnspiralized(final int[][] matrix) throws IllegalArgumentException {
имена функций должны быть записаны camelCase'ом: http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html#367
-0.5 балла

2017-10-14 12:47 UTC, annikura commented on Spiral/src/test/java/ru/spbau/annikura/spiral/CoordinateTest.java
> +package test.java.ru.spbau.annikura.spiral;
Переместила. Но видеть тесты maven'у это не очень помогло.

2017-10-14 12:49 UTC, annikura commented on Spiral/src/main/java/ru/spbau/annikura/spiral/Spiral.java
> +    public static void PrintUnspiralized(final int[][] matrix) throws IllegalArgumentException {
Поправила оба. Ну бес попутал. 

P.S. Любая ошибка карается сразу без предупреждений?

2017-10-16 14:46 UTC, jzuken commented on Spiral/src/main/java/ru/spbau/annikura/spiral/Spiral.java
> +    public static void PrintUnspiralized(final int[][] matrix) throws IllegalArgumentException {
не любая, про соответствие стайлгайду я непрерывно говорю, начиная с первой пары

2017-10-18 14:08 UTC, annikura commented on Spiral/src/test/java/ru/spbau/annikura/spiral/CoordinateTest.java
> +package test.java.ru.spbau.annikura.spiral;
Теперь помогло.

2017-10-18 14:08 UTC, annikura commented on Spiral/src/main/java/ru/spbau/annikura/spiral/Spiral.java
> +    public static void PrintUnspiralized(final int[][] matrix) throws IllegalArgumentException {
Ну окей

2017-10-22 14:28 UTC, jzuken requested changes

2017-10-22 14:28 UTC, jzuken commented on Spiral/pom.xml
> +            <groupId>org.testng</groupId>
а лучше не стало:
`Tests run: 0, Failures: 0, Errors: 0, Skipped: 0`
зачем тут TestNG? всё плохо именно из-за него. вот тут пишут, как это поправить: https://stackoverflow.com/questions/14984093/tests-stuck-on-configuring-testng-with-testng652configurator, но я бы просто убрал TestNG и оставил JUnit. ну или наоборот, но оба сразу это перебор
-1 балл

2017-10-22 14:28 UTC, jzuken commented on Spiral/src/main/java/ru/spbau/annikura/spiral/Coordinate.java
> +    private int x, y;
лучше в две строки

2017-10-24 01:00 UTC, annikura commented on Spiral/pom.xml
> +            <groupId>org.testng</groupId>
![mvntest](https://user-images.githubusercontent.com/18505735/31920091-5e55a7e8-b86f-11e7-8860-d0d441e6bbf1.png)

Не поняла, за что минус балл. На всякий случай даже попробовала сделать чистый git clone. Тесты всё равно запускаются и работают исправно. TestNG и JUnit это действительно избыточно, но не работало оно не из-за этого.

2017-10-27 04:51 UTC, annikura commented on Spiral/src/main/java/ru/spbau/annikura/spiral/Coordinate.java
> +    private int x, y;
Сделано.

2017-10-27 04:54 UTC, annikura commented on Spiral/pom.xml
> +            <groupId>org.testng</groupId>
Я убрала все лишние зависимости (их там не одна, а даже 2 было). Но опять же повторюсь, что у меня текстирование работало и до этого коммита и я готова это продемонстрировать, если нужно. Но в таком случае я честно не понимаю, как оно могло не работать у вас.

2017-11-06 10:30 UTC, merged