Lab 3
annikura/java pull request #3
Opened 2017-10-04 15:24 UTC by annikura

2017-10-20 09:36 UTC, jzuken requested changes

2017-10-20 09:36 UTC, jzuken commented on Trie/src/main/java/ru/spbau/annikura/trie/Trie.java
> +     * Adds string to trie.
асимптотику операций ещё полезно указывать

2017-10-20 09:36 UTC, jzuken commented on Trie/src/main/java/ru/spbau/annikura/trie/Trie.java
> +public class Trie implements Serializable {
по условию ещё требуются методы serialize() и deserialize()
и тестов на эту функциональность тоже не вижу
-1

2017-10-27 04:05 UTC, annikura commented on Trie/src/main/java/ru/spbau/annikura/trie/Trie.java
> +public class Trie implements Serializable {
Сами методы я забыла запушить, так мне и надо. Тесты появились. Теперь всё есть.

2017-10-27 04:35 UTC, annikura commented on Trie/src/main/java/ru/spbau/annikura/trie/Trie.java
> +     * Adds string to trie.
Теперь указала.

2017-11-06 10:37 UTC, jzuken requested changes

2017-11-06 10:37 UTC, jzuken commented on Trie/src/test/java/ru/spbau/annikura/trie/TrieTest.java
> +    public void serializationAndDeserialization() throws IOException, ClassNotFoundException {
я на паре просил разные тесты на сериализацию и десериализацию, добавьте их тоже, пожалуйста

2017-12-26 11:37 UTC, annikura commented on Trie/src/test/java/ru/spbau/annikura/trie/TrieTest.java
> +    public void serializationAndDeserialization() throws IOException, ClassNotFoundException {
Добавила

2017-12-27 17:44 UTC, merged