init commit
annikura/java pull request #6
Opened 2017-10-11 17:55 UTC by annikura

2017-10-21 08:41 UTC, jzuken requested changes

2017-10-21 08:41 UTC, jzuken commented on ZipFile/src/test/java/ru/spbau/annikura/zipfile/ZipFileTest.java
> +            ZipFile.unzipFilesIf(zipFile, zipFile.getParent() + File.separator + "result", s -> s.contains("f"));
`java.io.FileNotFoundException: src\test\resources\filtrationTest\file.zip (Не удается найти указанный файл)`
не вижу такого файлика

2017-10-21 08:41 UTC, jzuken commented on ZipFile/src/test/java/ru/spbau/annikura/zipfile/ZipFileTest.java
> +            assertEquals(true, newFile.delete());
этот ассерт тоже под виндой не проходит

2017-10-21 08:41 UTC, jzuken commented on ZipFile/src/main/java/ru/spbau/annikura/zipfile/ZipFile.java
> +     * @param zipInputStream
а где описания?
-0.5

2017-10-21 08:41 UTC, jzuken commented on ZipFile/src/main/java/ru/spbau/annikura/zipfile/ZipFile.java
> +    private static void unzipFile(ZipInputStream zipInputStream,
пора бы уже использовать аннотации NotNull/Nullable

2017-10-27 02:18 UTC, annikura commented on ZipFile/src/main/java/ru/spbau/annikura/zipfile/ZipFile.java
> +     * @param zipInputStream
Извините, но я не очень согласна с тем, что вы сняли баллы. Это ведь private метод и вы говорили, что туда вообще можно ничего написать. Я написала для себя, да и в комментарии выше описаний написано, что делает каждый из параметров. Для всех публичных методов описания присутствуют.

Добавила описания и к этому методу, но твёрдо считаю, что  снимать балы в данном случае не очень честно. Если на private-методы теперь накладываются те же требования, что и на публиные, объявите об этом, пожалуйста.

2017-10-27 02:19 UTC, annikura commented on ZipFile/src/main/java/ru/spbau/annikura/zipfile/ZipFile.java
> +    private static void unzipFile(ZipInputStream zipInputStream,
Написала.

2017-10-27 02:21 UTC, annikura commented on ZipFile/src/test/java/ru/spbau/annikura/zipfile/ZipFileTest.java
> +            assertEquals(true, newFile.delete());
Починила. Я почему-то в некоторых местах захардкодила разделитель.

2017-10-27 02:41 UTC, annikura commented on ZipFile/src/test/java/ru/spbau/annikura/zipfile/ZipFileTest.java
> +            ZipFile.unzipFilesIf(zipFile, zipFile.getParent() + File.separator + "result", s -> s.contains("f"));
Глупо вышло. По умолчанию создаваемый идеей gitignore логично игнорирует zip-файлы.

2017-10-27 06:29 UTC, jzuken commented on ZipFile/src/main/java/ru/spbau/annikura/zipfile/ZipFile.java
> +     * @param zipInputStream
в целом согласен, и если бы этого @param zipInputStream тут вообще не было, я бы слова не сказал? а так неаккуратно и некрасиво получается, код от этого лучше не становится

2017-10-27 06:47 UTC, annikura commented on ZipFile/src/main/java/ru/spbau/annikura/zipfile/ZipFile.java
> +     * @param zipInputStream
Да, я поняла мотивацию и учту на будущее; но за полбалла всё равно обидно. Вроде как говорилось, что к приватным методам можно и не писать вовсе, а я написала и получила штраф. Но окей, это уже вам решать.

2017-11-06 10:46 UTC, jzuken requested changes

2017-11-06 10:46 UTC, jzuken commented on ZipFile/src/main/java/UnzipMatchingFiles.java
> +import com.sun.istack.internal.NotNull;
аннотации то вы добавили, а мавену забыли сказать, что в проекте добавилась внешняя зависимость. в итоге в консоли ничего не собирается. я же даже специально этот момент отразил отдельно в [табличке](https://docs.google.com/spreadsheets/d/1hRcQk4FmwK0mZYWKbvjGx-ypwqxcNjtXlRab-WDj7Ek/edit#gid=0). будьте внимательнее!
-1
кстати, я имел в виду org.jetbrains.annotations.NotNull, там ещё кучка полезных аннотаций есть. но это некритично тут

2017-11-26 14:11 UTC, merged