Lab6.set
annikura/java pull request #8
Opened 2017-10-18 02:19 UTC by annikura

2017-10-23 16:19 UTC, jzuken requested changes

2017-10-23 16:19 UTC, jzuken commented on Set/src/main/java/ru/spbau/annikura/set/Set.java
> +     * @param t
нехорошо такие висящие теги оставлять

2017-10-23 16:19 UTC, jzuken commented on Set/src/test/java/ru/spbau/annikura/set/SetTest.java
> +        SetWrapper<String> setWrapper = new SetWrapper<String>();
тут справа можно тип в угловых скобках не писать

2017-10-27 00:34 UTC, annikura commented on Set/src/main/java/ru/spbau/annikura/set/Set.java
> +     * @param t
Технически, мне казалось, что я объяснила, что с этим значением происходит в комментарии выше.
Но окей, надо так надо. Буду писать

2017-10-27 00:35 UTC, annikura commented on Set/src/test/java/ru/spbau/annikura/set/SetTest.java
> +        SetWrapper<String> setWrapper = new SetWrapper<String>();
Done.

2017-10-27 06:26 UTC, jzuken commented on Set/src/main/java/ru/spbau/annikura/set/Set.java
> +     * @param t
ну просто такие висящие теги некрасиво смотрятся + когда вы смотрите в сгенерённую документацию, что это за параметр такой, вы будете смотреть именно в эту секцию, а не парсить потенциально длинное описание метода в целом

2017-11-06 10:41 UTC, jzuken commented on Set/pom.xml
> +                    <source>1.7</source>
тогда уж 1.9 сразу бы, или хотя бы 1.8

2017-11-06 10:41 UTC, merged