Lab6.maybe
annikura/java pull request #9
Opened 2017-10-18 02:21 UTC by annikura

2017-11-05 15:57 UTC, jzuken requested changes

2017-11-05 15:57 UTC, jzuken commented on Maybe/pom.xml
> +    <dependencies>
а вот сюда надо добавить информацию о пакете с аннотациями, а то мавен из консоли это не собирает. про это даже есть отдельная строчка в [таблице со штрафами](https://docs.google.com/spreadsheets/d/1hRcQk4FmwK0mZYWKbvjGx-ypwqxcNjtXlRab-WDj7Ek/edit#gid=0)
-1

2017-11-05 15:57 UTC, jzuken commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +import com.sun.istack.internal.NotNull;
вообще я рассказывал про org.jetbrains.annotations.NotNull, но да ладно, и эти сойдут, если они больше нравятся :)

2017-11-05 15:57 UTC, jzuken commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +        throw new MaybeException("Invalid get. Maybe does not contain a value");
лучше придумать имя, говорящее о сути проблемы
и исключения тоже надо документировать

2017-11-05 15:57 UTC, jzuken commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +            return Maybe.nothing();
а тут правда надо создавать новый объект?

2017-11-05 15:57 UTC, jzuken commented on Maybe/src/main/java/ru/spbau/annikura/maybe/MaybeException.java
> +     * @param message
и снова пустой тег без комментария

2017-11-05 15:57 UTC, jzuken commented on Maybe/src/main/java/ru/spbau/annikura/maybe/SquareNumbers.java
> +public class SquareNumbers {
и класс без доков

2017-11-13 00:32 UTC, annikura commented on Maybe/pom.xml
> +    <dependencies>
Непривычка-с... Пофикшено.

2017-11-13 00:34 UTC, annikura commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +import com.sun.istack.internal.NotNull;
Как-то я даже и не вчиталась, что мне предложила идея. org.jetbrains.annotations.whatever выглядят лучше. На них хотя бы не висит "internal". Опыт показывает, что таким лучше не пользоваться.

2017-11-13 00:34 UTC, annikura commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +        throw new MaybeException("Invalid get. Maybe does not contain a value");
Принято-Сделано.

2017-11-13 00:36 UTC, annikura commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +            return Maybe.nothing();
Вообще, не надо, но на текущей стадии проекта ресурсы моей машины позволяют мне его создавать и запускать тесты без проблем :)
Заменила на статическое поле. Больше не создаю. Ну только один раз.

2017-11-13 00:38 UTC, annikura commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +            return Maybe.nothing();
А с другой стороны, это норма, что теперь все Nothing между собой равны?

2017-11-13 00:38 UTC, annikura commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +            return Maybe.nothing();
А с другой стороны, это норма, что все Nothing теперь равны между собой?

2017-11-13 00:40 UTC, annikura commented on Maybe/src/main/java/ru/spbau/annikura/maybe/MaybeException.java
> +     * @param message
Ай-вай... Непорядок. Починила.

2017-11-13 00:41 UTC, annikura commented on Maybe/src/main/java/ru/spbau/annikura/maybe/SquareNumbers.java
> +public class SquareNumbers {
Fixed. Класс с main нужно как-то отдельно помечать или особенно документировать или он в этом смысле ничем от других не отличается?

2017-11-17 04:29 UTC, jzuken commented on Maybe/src/main/java/ru/spbau/annikura/maybe/Maybe.java
> +            return Maybe.nothing();
вообще можно было просто this вернуть :)
то, что все Nothing теперь равны между собой, на мой взгляд, концептуально более верно, но в этой задаче я этого не требую

2017-11-17 04:32 UTC, jzuken commented on Maybe/src/main/java/ru/spbau/annikura/maybe/SquareNumbers.java
> +public class SquareNumbers {
я бы сказал, что он ничем не отличается, но подробно его документировать смысла мало. разве что в main() что-то интересное делается

2017-11-26 17:11 UTC, merged